# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fraud_scoring_pb2 as fraud__scoring__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fraud_scoring_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FraudScoringServiceStub(object):
    """=============================================================================
    Service Definition
    =============================================================================

    FraudScoringService is the primary entry point for transaction fraud evaluation.
    It orchestrates calls to the rule engine, ML scoring, and graph analysis services,
    then combines their outputs into a single fraud score and decision.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScoreTransaction = channel.unary_unary(
                '/fraud_platform.scoring.FraudScoringService/ScoreTransaction',
                request_serializer=fraud__scoring__pb2.TransactionEvent.SerializeToString,
                response_deserializer=fraud__scoring__pb2.FraudScore.FromString,
                _registered_method=True)
        self.GetDecision = channel.unary_unary(
                '/fraud_platform.scoring.FraudScoringService/GetDecision',
                request_serializer=fraud__scoring__pb2.DecisionRequest.SerializeToString,
                response_deserializer=fraud__scoring__pb2.FraudDecisionResponse.FromString,
                _registered_method=True)
        self.GetScoringHealth = channel.unary_unary(
                '/fraud_platform.scoring.FraudScoringService/GetScoringHealth',
                request_serializer=fraud__scoring__pb2.HealthRequest.SerializeToString,
                response_deserializer=fraud__scoring__pb2.HealthResponse.FromString,
                _registered_method=True)


class FraudScoringServiceServicer(object):
    """=============================================================================
    Service Definition
    =============================================================================

    FraudScoringService is the primary entry point for transaction fraud evaluation.
    It orchestrates calls to the rule engine, ML scoring, and graph analysis services,
    then combines their outputs into a single fraud score and decision.
    """

    def ScoreTransaction(self, request, context):
        """ScoreTransaction evaluates a single transaction event against all fraud
        detection subsystems and returns a comprehensive fraud score.
        This is the hot path — latency-critical, called for every inbound transaction.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDecision(self, request, context):
        """GetDecision retrieves a previously computed fraud decision by transaction ID.
        Used for post-scoring lookups, audit trails, and dispute resolution workflows.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScoringHealth(self, request, context):
        """GetScoringHealth returns the health status of the scoring service and its
        downstream dependencies. Used by Kubernetes liveness/readiness probes and
        the platform monitoring dashboard.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FraudScoringServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScoreTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.ScoreTransaction,
                    request_deserializer=fraud__scoring__pb2.TransactionEvent.FromString,
                    response_serializer=fraud__scoring__pb2.FraudScore.SerializeToString,
            ),
            'GetDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDecision,
                    request_deserializer=fraud__scoring__pb2.DecisionRequest.FromString,
                    response_serializer=fraud__scoring__pb2.FraudDecisionResponse.SerializeToString,
            ),
            'GetScoringHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScoringHealth,
                    request_deserializer=fraud__scoring__pb2.HealthRequest.FromString,
                    response_serializer=fraud__scoring__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fraud_platform.scoring.FraudScoringService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fraud_platform.scoring.FraudScoringService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FraudScoringService(object):
    """=============================================================================
    Service Definition
    =============================================================================

    FraudScoringService is the primary entry point for transaction fraud evaluation.
    It orchestrates calls to the rule engine, ML scoring, and graph analysis services,
    then combines their outputs into a single fraud score and decision.
    """

    @staticmethod
    def ScoreTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fraud_platform.scoring.FraudScoringService/ScoreTransaction',
            fraud__scoring__pb2.TransactionEvent.SerializeToString,
            fraud__scoring__pb2.FraudScore.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fraud_platform.scoring.FraudScoringService/GetDecision',
            fraud__scoring__pb2.DecisionRequest.SerializeToString,
            fraud__scoring__pb2.FraudDecisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScoringHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fraud_platform.scoring.FraudScoringService/GetScoringHealth',
            fraud__scoring__pb2.HealthRequest.SerializeToString,
            fraud__scoring__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
