# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import graph_analysis_pb2 as graph__analysis__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in graph_analysis_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GraphAnalysisServiceStub(object):
    """=============================================================================
    Service Definition
    =============================================================================

    GraphAnalysisService performs real-time and batch graph-based fraud analysis.
    It maintains an evolving transaction graph and exposes pattern detection
    capabilities over the graph topology.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeGraph = channel.unary_unary(
                '/fraud_platform.graph.GraphAnalysisService/AnalyzeGraph',
                request_serializer=graph__analysis__pb2.GraphAnalysisRequest.SerializeToString,
                response_deserializer=graph__analysis__pb2.GraphAnalysisResult.FromString,
                _registered_method=True)
        self.DetectPatterns = channel.unary_unary(
                '/fraud_platform.graph.GraphAnalysisService/DetectPatterns',
                request_serializer=graph__analysis__pb2.GraphAnalysisRequest.SerializeToString,
                response_deserializer=graph__analysis__pb2.GraphAnalysisResult.FromString,
                _registered_method=True)
        self.GetGraphHealth = channel.unary_unary(
                '/fraud_platform.graph.GraphAnalysisService/GetGraphHealth',
                request_serializer=graph__analysis__pb2.HealthRequest.SerializeToString,
                response_deserializer=graph__analysis__pb2.HealthResponse.FromString,
                _registered_method=True)


class GraphAnalysisServiceServicer(object):
    """=============================================================================
    Service Definition
    =============================================================================

    GraphAnalysisService performs real-time and batch graph-based fraud analysis.
    It maintains an evolving transaction graph and exposes pattern detection
    capabilities over the graph topology.
    """

    def AnalyzeGraph(self, request, context):
        """AnalyzeGraph performs a targeted neighborhood analysis around the entities
        involved in a specific transaction. Returns a graph-based risk score and
        any structural patterns detected in the local subgraph.
        Latency target: <40ms p99 for 2-hop neighborhood traversals.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectPatterns(self, request, context):
        """DetectPatterns performs a broader, more compute-intensive pattern scan
        across the transaction graph. May examine multi-hop paths and community
        structures. Suitable for near-real-time or batch processing use cases.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGraphHealth(self, request, context):
        """GetGraphHealth returns the health status of the graph analysis service,
        including graph database connectivity and cache statistics.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GraphAnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeGraph,
                    request_deserializer=graph__analysis__pb2.GraphAnalysisRequest.FromString,
                    response_serializer=graph__analysis__pb2.GraphAnalysisResult.SerializeToString,
            ),
            'DetectPatterns': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectPatterns,
                    request_deserializer=graph__analysis__pb2.GraphAnalysisRequest.FromString,
                    response_serializer=graph__analysis__pb2.GraphAnalysisResult.SerializeToString,
            ),
            'GetGraphHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGraphHealth,
                    request_deserializer=graph__analysis__pb2.HealthRequest.FromString,
                    response_serializer=graph__analysis__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fraud_platform.graph.GraphAnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fraud_platform.graph.GraphAnalysisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GraphAnalysisService(object):
    """=============================================================================
    Service Definition
    =============================================================================

    GraphAnalysisService performs real-time and batch graph-based fraud analysis.
    It maintains an evolving transaction graph and exposes pattern detection
    capabilities over the graph topology.
    """

    @staticmethod
    def AnalyzeGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fraud_platform.graph.GraphAnalysisService/AnalyzeGraph',
            graph__analysis__pb2.GraphAnalysisRequest.SerializeToString,
            graph__analysis__pb2.GraphAnalysisResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectPatterns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fraud_platform.graph.GraphAnalysisService/DetectPatterns',
            graph__analysis__pb2.GraphAnalysisRequest.SerializeToString,
            graph__analysis__pb2.GraphAnalysisResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGraphHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fraud_platform.graph.GraphAnalysisService/GetGraphHealth',
            graph__analysis__pb2.HealthRequest.SerializeToString,
            graph__analysis__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
