# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ml_scoring_pb2 as ml__scoring__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ml_scoring_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MLScoringServiceStub(object):
    """=============================================================================
    Service Definition
    =============================================================================

    MLScoringService provides real-time fraud probability predictions using
    trained machine learning models. Supports model versioning, canary
    deployments, and shadow scoring for offline evaluation.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictFraud = channel.unary_unary(
                '/fraud_platform.ml.MLScoringService/PredictFraud',
                request_serializer=ml__scoring__pb2.PredictionRequest.SerializeToString,
                response_deserializer=ml__scoring__pb2.PredictionResult.FromString,
                _registered_method=True)
        self.GetModelInfo = channel.unary_unary(
                '/fraud_platform.ml.MLScoringService/GetModelInfo',
                request_serializer=ml__scoring__pb2.ModelInfoRequest.SerializeToString,
                response_deserializer=ml__scoring__pb2.ModelInfo.FromString,
                _registered_method=True)
        self.GetMLHealth = channel.unary_unary(
                '/fraud_platform.ml.MLScoringService/GetMLHealth',
                request_serializer=ml__scoring__pb2.HealthRequest.SerializeToString,
                response_deserializer=ml__scoring__pb2.HealthResponse.FromString,
                _registered_method=True)


class MLScoringServiceServicer(object):
    """=============================================================================
    Service Definition
    =============================================================================

    MLScoringService provides real-time fraud probability predictions using
    trained machine learning models. Supports model versioning, canary
    deployments, and shadow scoring for offline evaluation.
    """

    def PredictFraud(self, request, context):
        """PredictFraud runs inference on a set of transaction features and returns
        a fraud probability score with anomaly flags.
        This is the hot path — called for every transaction during scoring.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """GetModelInfo retrieves metadata about a deployed model, including version,
        accuracy metrics, and training recency. Used by the monitoring dashboard
        and model governance workflows.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMLHealth(self, request, context):
        """GetMLHealth returns the health status of the ML scoring service, including
        model loading state and GPU utilization.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLScoringServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictFraud': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictFraud,
                    request_deserializer=ml__scoring__pb2.PredictionRequest.FromString,
                    response_serializer=ml__scoring__pb2.PredictionResult.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=ml__scoring__pb2.ModelInfoRequest.FromString,
                    response_serializer=ml__scoring__pb2.ModelInfo.SerializeToString,
            ),
            'GetMLHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMLHealth,
                    request_deserializer=ml__scoring__pb2.HealthRequest.FromString,
                    response_serializer=ml__scoring__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fraud_platform.ml.MLScoringService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fraud_platform.ml.MLScoringService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MLScoringService(object):
    """=============================================================================
    Service Definition
    =============================================================================

    MLScoringService provides real-time fraud probability predictions using
    trained machine learning models. Supports model versioning, canary
    deployments, and shadow scoring for offline evaluation.
    """

    @staticmethod
    def PredictFraud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fraud_platform.ml.MLScoringService/PredictFraud',
            ml__scoring__pb2.PredictionRequest.SerializeToString,
            ml__scoring__pb2.PredictionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fraud_platform.ml.MLScoringService/GetModelInfo',
            ml__scoring__pb2.ModelInfoRequest.SerializeToString,
            ml__scoring__pb2.ModelInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMLHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fraud_platform.ml.MLScoringService/GetMLHealth',
            ml__scoring__pb2.HealthRequest.SerializeToString,
            ml__scoring__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
