# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rule_engine_pb2 as rule__engine__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rule_engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RuleEngineServiceStub(object):
    """=============================================================================
    Service Definition
    =============================================================================

    RuleEngineService evaluates transactions against a managed catalog of
    deterministic fraud detection rules. Rules are versioned and hot-reloadable
    without service restart.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EvaluateRules = channel.unary_unary(
                '/fraud_platform.rules.RuleEngineService/EvaluateRules',
                request_serializer=rule__engine__pb2.RuleEvalRequest.SerializeToString,
                response_deserializer=rule__engine__pb2.RuleEvalResult.FromString,
                _registered_method=True)
        self.GetRuleHealth = channel.unary_unary(
                '/fraud_platform.rules.RuleEngineService/GetRuleHealth',
                request_serializer=rule__engine__pb2.HealthRequest.SerializeToString,
                response_deserializer=rule__engine__pb2.HealthResponse.FromString,
                _registered_method=True)


class RuleEngineServiceServicer(object):
    """=============================================================================
    Service Definition
    =============================================================================

    RuleEngineService evaluates transactions against a managed catalog of
    deterministic fraud detection rules. Rules are versioned and hot-reloadable
    without service restart.
    """

    def EvaluateRules(self, request, context):
        """EvaluateRules runs the full rule catalog against a transaction and returns
        an aggregate rule score with individual match details.
        Latency target: <20ms p99 for up to 500 active rules.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRuleHealth(self, request, context):
        """GetRuleHealth returns the health status of the rule engine, including
        the number of loaded rules and last reload timestamp.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuleEngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EvaluateRules': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateRules,
                    request_deserializer=rule__engine__pb2.RuleEvalRequest.FromString,
                    response_serializer=rule__engine__pb2.RuleEvalResult.SerializeToString,
            ),
            'GetRuleHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuleHealth,
                    request_deserializer=rule__engine__pb2.HealthRequest.FromString,
                    response_serializer=rule__engine__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fraud_platform.rules.RuleEngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fraud_platform.rules.RuleEngineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuleEngineService(object):
    """=============================================================================
    Service Definition
    =============================================================================

    RuleEngineService evaluates transactions against a managed catalog of
    deterministic fraud detection rules. Rules are versioned and hot-reloadable
    without service restart.
    """

    @staticmethod
    def EvaluateRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fraud_platform.rules.RuleEngineService/EvaluateRules',
            rule__engine__pb2.RuleEvalRequest.SerializeToString,
            rule__engine__pb2.RuleEvalResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRuleHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fraud_platform.rules.RuleEngineService/GetRuleHealth',
            rule__engine__pb2.HealthRequest.SerializeToString,
            rule__engine__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
